feat: load env variables values conditionally
portittech/pay-with-toonie-js-sdk pull request #38
Opened 2024-03-01 16:57 UTC by marco-kuama

2024-03-02 10:15 UTC, kuamanet requested changes

2024-03-02 10:15 UTC, kuamanet commented on rollup.config.js
> +    break;
```suggestion
    break;
    default:
        throw new Error(`The requested ${env} env is not supported`)
```

2024-03-02 10:15 UTC, kuamanet commented on rollup.config.js
> +const env = "prod";
Shouldn't this be `const env = process.env.ENVIRONMENT`?

2024-03-04 16:25 UTC, kuamanet commented on src/App.svelte
> +  const toonieRedirectUrl = "https://www.toonieglobal.com/"
Do we want to make this an env variable? Or will it always be this one?
```suggestion
  const redirectUrl = "https://www.toonieglobal.com/"
```

2024-03-04 16:28 UTC, marco-kuama commented on src/App.svelte
> +  const toonieRedirectUrl = "https://www.toonieglobal.com/"
I'm gonna add a comment because it is a temporary solution we decided with Gian to not allow the user to see the data about the payment when he comes back after finishing the payment

2024-03-04 16:41 UTC, kuamanet approved these changes

2024-03-04 16:41 UTC, merged